### PR TITLE
feat: integrate casdoor into springcloud alibaba

### PR DESCRIPTION
**Pull request by imp2002**
Fix: https://github.com/casdoor/casdoor/issues/624

### CODE REVIEW

**Comment by hsluoyz** [comment]
@imp2002 where is the SpringCloud? I didn't see it in the code. Also can you add the README? How are the users supposed to use it?

**Comment by imp2002** [comment]
> @imp2002 where is the SpringCloud? I didn't see it in the code. Also can you add the README? How are the users supposed to use it?

ok

**Comment by hsluoyz** [comment]
@conghuhu

**Comment by conghuhu** [comment]
@imp2002 I would like to ask, the current implementation of your cloud seems to be basically similar to the implementation logic of casdoor spring boot starter. Is it possible to introduce the casdoor spring boot starter into the spring cloud? There is no need to do this casdoor spring cloud starter.

**Pull request closed without merging**
